package com.normurodov_nazar.savol_javob.MFunctions;

public class Keys {

    public static final String token = "Token";
    public static final String sharedPreferences = "com.normurodov_nazar.savol_javob.preferences";
    public static final String p = "phone";
    public static final String logged = "logged";
    public static final String seen = "Seen";
    public static final String number = "Number";
    public static final String users = "Users";
    public static final String appNumbers = "AppNumbers";
    public static final String name = "Name";
    public static final String surname = "Surname";
    public static final String imageSize = "ImageSize";
    public static final String id = "User Id";
    public static final String chats = "Chats";
    public static final String verificationId = "verificationId";
    public static final String units = "QuestionOpportunity";
    public static final String numberOfMyPublishedQuestions = "numberOfMyPublishedQuestions";
    public static final String numberOfMyAnswers = "numberOfMyAnswers";
    public static final String numberOfCorrectAnswers = "numberOfCorrectAnswers";
    public static final String numberOfIncorrectAnswers = "numberOfIncorrectAnswers";
    public static final String errorInternetWhenNumber = "A network error (such as timeout, interrupted connection or unreachable host) has occurred.";
    public static final String errorNumberInvalid = "The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code]. [ TOO_SHORT ]";
    public static final String errorRecaptcha = "";
    public static final String errorVerificationCode = "The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user.";
    public static final String errorInternetWhenCode = "A network error (such as timeout, interrupted connection or unreachable host) has occurred.";
    public static final String message = "Message";
    public static final String time = "Time";
    public static final String sender = "Sender";
    public static final String type = "Type";
    public static final String textMessage = "TextMessage";
    public static final String imageMessage = "ImageMessage";
    public static final String chatId = "ChatId";
    public static final String publicQuestions = "PublicQuestions";
    public static final String read = "Read";
    public static final String fromChat = "From chat";
    public static final String newMessagesTo = "UnreadMessagesBy:";
    public static final String theme = "Theme";
    public static final String allQuestions = "AllQuestions";
    public static final String question = "Question";
    public static final String answer = "Answer";
    public static String correct = "Correct";
    public static String incorrect = "Incorrect";
    public static String savedQuestions = "SavedQuestions";
    public static String questionLimit = "QuestionLimit";
    public static String unitsForPerDay = "UnitsForPerDay";
    public static String visibleTime = "PublicUntil";
    public static String needQuestions = "NeedQuestions";
    public static String order = "Order";
    public static String divider = "Divider";
    public static String status = "Status";
}
